title="title"
etag="etag"
id="id"
mime="mime"
file_name="file"
desired_class="desired_class"

file_type="http://schemas.google.com/docs/2007#file"
folder_type="http://schemas.google.com/docs/2007#folder"
item_type="http://schemas.google.com/docs/2007#item"